GET http://localhost:63975/api/driver

###

POST http://localhost:63975/api/driver
Content-Type: application/json

{
  "driverId": "test-9",
  "name": "Shane Gray"
}

###

POST http://localhost:63975/api/driver/test-9/load-van
###

POST http://localhost:63975/api/driver/test-9/run-started
###

POST http://localhost:63975/api/driver/test-9/run-complete
