@base = http://localhost:64982/api/package

GET {{base}}

### Manifest Added (forecast)
POST {{base}}
Content-Type: application/json

{
  "barcode": "im-unique",
  "address": {
    "addressText": "some road, somewhere, county nowhere",
    "country": "Ireland"
  },
  "customer": {
    "firstName": "John",
    "surname": "Smith"
  }
}

### HIP
POST {{base}}/im-unique/hip
Content-Type: application/json

{
  "barcode": "im-unique",
  "depot": "BAC"
}


### DIP
POST {{base}}/im-unique/dip
Content-Type: application/json

{
  "barcode": "im-unique",
  "depot": "SXL"
}


### VOP
POST {{base}}/im-unique/vop
Content-Type: application/json

{
  "barcode": "im-unique",
  "driver": {
    "driverId": "test-9",
    "driverName": "Shane Gray"
  }
}

### DNC
POST {{base}}/im-unique/dnc
Content-Type: application/json

{
  "barcode": "im-unique",
  "failedReason": "I got lost 🤷"
}

### VIP
POST {{base}}/im-unique/vip
Content-Type: application/json

{
  "barcode": "im-unique",
  "driver": {
    "driverId": "test-9",
    "driverName": "Shane Gray"
  }
}

### POD
POST {{base}}/im-unique/pod
Content-Type: application/json

{
  "barcode": "im-unique",
  "signature": {
    "customerSignature": "✍️",
    "initials": "JS"
  },
  "latLon": {
    "lat": 53.454323,
    "lon": -6.154629
  }
}
