version: '3'

services: 
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27020:27017"
    restart: unless-stopped
  rabbit:
    image: rabbitmq:3.6.8-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: unless-stopped  